### ISSUE TITLE
Porting php-zmq to PHP7

### ISSUE THREAD

**Issue by funkymunkey** [mkoppanen/php-zmq#155] opened 2015-05-31 22:26 UTC
Hi,

Do you have any plans of porting this extension to PHP7? or should i do it myself?

Regards

**Comment by WillSkates** [comment] 2015-07-17 09:33
Is it clear what work needs to be done in order to port it?

**Comment by mkoppanen** [comment] 2015-07-20 12:36
@WillSkates,

Some of the internal APIs have changed. It shouldn't be a huge task but probably will be quite hard to support PHP 5 and 7 due to excess ifdefs. I would say that let's create a completely new branch for PHP7 and backport only critical fixes to PHP5 version. 

:+1: ?

**Comment by bnikola** [comment] 2015-07-20 12:54
I'm in favor of Mikko's suggestion, a new branch for PHP 7 would be awesome, and having the extension up and running before initial PHP 7 release would be excellent. :)

**Comment by rinu** [comment] 2015-07-20 13:50
PHP 7 branch sounds great.

**Comment by phuedx** [comment] 2015-07-20 14:34
Having a new branch would make it easier to focus only on PHP7 specifics, allowing you to move forward quickly but I can't help but feel that separating the core of the extension from the PHP API-specific parts – handling PHP5 and PHP7 at the same time (but in different files!) – would be cleaner. I'm a little on the fence about this.

**Comment by WillSkates** [comment] 2015-09-16 10:58
@phuedx I would prefer having the new branch just because it establishes at least to me that it's fixes that will be back ported and not features. If you would like to back port new features to php5 as well then I fully support your idea.

**Comment by bweston92** [comment] 2015-09-27 13:10
Any updates for PHP 7 support?

**Comment by WillSkates** [comment] 2015-10-16 11:29
@mkoppanen Could you please spell it out for me a little bit. I use this module a lot and would love to contribute in some way but if I'm honest I have absolutely no idea what really needs doing.

**Comment by mkoppanen** [comment] 2015-10-16 12:36
Hey,

there has been several API changes between PHP 5 and PHP 7. This would probably be a good place to start: https://wiki.php.net/phpng-upgrading

**Comment by M1ke** [comment] 2015-10-27 10:05
@phuedx I agree with @WillSkates in that a separate branch more clearly indicates support. The move to PHP 7 might not be as quick as, say 5.5 to 5.6, but there's an argument that beggars can't be choosers - if you want to use cutting edge features, you use the cutting edge version. Branching for 7 means far less worry about conflicts. If it turns out once the work is done that the whole extension can easily support both it can merge back in, but getting a viable extension released for 7 as quickly as possible seems the best goal.

We use php-zmq on a large production system and it will currently be the one thing preventing us from moving to 7 for our whole stack. Has anyone who's tried to run it got a list of issues that come up? I've not worked on extensions before but would like to pitch in if there are existing efforts.

**Comment by mkoppanen** [comment] 2015-10-30 20:12
I am currently on a bit of a time crunch but I am happy to mentor if anyone has time to get this work going. In my opinion we should create PHP 7 branch, start the migration there and then eventually tag the PHP 5.x version as a dead tree. It seems unlikely that we can support PHP 5.x and 7 in the same extension as the changes are quite radical to the internal API.

I would love to say that I can dedicate time to the migration but I don't want to make promises that I cannot keep.

**Comment by mkoppanen** [comment] 2015-11-01 20:05
I pushed an initial version of the phpng into a branch called php7. There are still quite a few rough edges but at least this far it compiles and runs to a degree. The following tests are currently failing:

````
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test adding / removing items [tests/007-addremovepoll.phpt]
Test remove invalid id from ZMQPoll [tests/012-pollsetremoveinvalid.phpt]
Test clearing and reusing ZMQPoll [tests/013-pollclearandreuse.phpt]
Test basic callback usage [tests/015-callback.phpt]
Test that callback is only called on new socket [tests/017-callbackonlyonnewsocket.phpt]
Test callback arguments on persistent and non-persistent socket [tests/018-callbackpersistent.phpt]
Test callback edge-cases [tests/019-callbackinvalidsignature.phpt]
Test throwing exception from callback [tests/020-exceptionincallback.phpt]
Test warning in callback [tests/021-callbackwarning.phpt]
Test that high-watermark works [tests/022-highwatermark.phpt]
Test that failing callback does not add socket to plist [tests/023-failedcallback.phpt]
Test send / recv with an XREQ and XREP device [tests/029-xrepxreqdevice.phpt]
Test device capture [tests/035-capture.phpt]
Test device callbacks [tests/036-device.phpt]
Test device deprecated args [tests/037-device-deprecated.phpt]
Test for Github issue #49 [tests/bug_gh_49.phpt]
Test for Github issue #50 [tests/bug_gh_50.phpt]
=====================================================================
````

**Comment by phuedx** [comment] 2015-11-01 20:09
> I would love to say that I can dedicate time to the migration but I don't want to make promises that I cannot keep.

I'm in very much the same situation.

> I pushed an initial version of the phpng into a branch called php7. There are still quite a few rough edges but at least this far it compiles and runs to a degree.

Wowzers! That's not a bad result for a first attempt.

**Comment by rinu** [comment] 2015-11-02 15:27
Am I doing it wrong? Tried compiling php7 branch on Ubuntu 15.04.
zmq.c:93:31: fatal error: zmq_object_access.c: No such file or directory

**Comment by mkoppanen** [comment] 2015-11-02 16:20
@rinu, looks like I missed git add for that file. Fixing now!

**Comment by WillSkates** [comment] 2015-11-02 18:09
Looks like this will be my evening. See you guys soon.

**Comment by rinu** [comment] 2015-11-04 16:02
Compiled fine and tested it just now, works perfectly for me.

**Comment by mkoppanen** [comment] 2015-11-04 17:38
@WillSkates I added the missing file to the repo but not yet to package.xml

**Comment by mkoppanen** [comment] 2015-11-08 20:32
@WillSkates should be fixed now

**Comment by mkoppanen** [comment] 2015-11-13 01:10
I fixed the CZMQ parts as well and it looks like pretty much everything is functional now

**Comment by WillSkates** [comment] 2015-11-14 00:31
Thank  you so much @mkoppanen is there a way of debugging segfaults with travis? My googling has come up short.

**Comment by mkoppanen** [comment] 2015-11-17 11:30
@WillSkates Maybe you could try setting coredump path and upload the dump somewhere? Does the error happen during tests? If yes, running tests with valgrind might work

**Comment by zahlprish** [comment] 2015-11-25 21:34
So I have attempted to install the ZMQ php7 branch on a newly provisioned server with PHP7. I feel like I am pretty close to getting it all set up but am running into a segment fault core dump issue. When I run the "make test" command, it appears only one thing is failing:
FAIL: Test clearing and reusing ZMQPoll [tests/013-pollclearandreuse.phpt]

So I went ahead and investigated this core dump with dbg and come up with:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  php_zmq_fd_cast (stream=<optimized out>, cast_as=<optimized out>, ret=0x7fff68854c9c) at /etc/php-zmq/zmq_fd_stream.c:68
68					if (zmq_getsockopt(intern->socket->z_socket, ZMQ_FD, (int*) ret, &optsiz) != 0) {
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'

Any thoughts, comments, potential direction to remedying this would be greatly appreciated!

**Comment by M1ke** [comment] 2016-01-07 16:09
If the current php7 branch works, is it possible for someone to note down the steps required to compile the extension on a Ubuntu machine? I've previously compiled the extension from the pecl source, but this seems to lack `./configure` or a `makefile` so I am uncertain where to begin. I tried running `autoconf config.m4` but received `config.m4:75: error: _AC_LANG_ABBREV: unknown language: _AC_LANG`

**Comment by zprisk** [comment] 2016-01-07 16:21
[unbuntu-zmq-php7-install.txt](https://github.com/mkoppanen/php-zmq/files/81370/unbuntu-zmq-php7-install.txt)

Not sure if this will help at all M1ke, but I have attached a copy of the current steps I use to install php on my ubuntu php 7 server. I have been able to get everything to work/install correctly, except I have one test fail (FAIL: Test clearing and reusing ZMQPoll) when I run 'make test'

**Comment by M1ke** [comment] 2016-01-07 17:05
That's compiled OK but I get a segmentation fault when code tries to use the bindings.

When running `./run-tests` I get the following message:

    PHP         : /usr/bin/php 
    Warning: PHP Startup: Unable to load dynamic library 'modules/zmq.so' - modules/zmq.so: cannot open shared object file: No such file or directory in Unknown on line 0

Then all the tests are skipped. I've added `extension=zmq.so` to the end of `/etc/php/7.0/cli/php.ini`

**Comment by zprisk** [comment] 2016-01-07 17:10
I've never used './run-tests', when testing I run 'sudo make test' within the php-zmq directory.

**Comment by mkoppanen** [comment] 2016-01-07 17:11
@M1ke:

when you have cloned the extension and changed to php7 branch the following should do:

```
phpize
./configure --with-php-config=/path/to/php7/bin/php-config
make
make test
make install 
```

**Comment by zprisk** [comment] 2016-01-07 17:31
@M1ke If you are able to get it going, I would definitely be interested in the steps you took to get there.

**Comment by M1ke** [comment] 2016-01-07 17:42
Why do you run `make test` with `sudo`? Your instructions seem to feature running all commands as root, though generally only the `make install` step should need root.

Running `make test` gives me:

> /bin/bash /home/m1ke/tmp/php-zmq/libtool --mode=install cp ./zmq.la /home/m1ke/tmp/php-zmq/modules
> libtool: install: cp ./.libs/zmq.so /home/m1ke/tmp/php-zmq/modules/zmq.so
> libtool: install: cp ./.libs/zmq.lai /home/m1ke/tmp/php-zmq/modules/zmq.la
> libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /home/m1ke/tmp/php-zmq/modules
> Libraries have been installed in:
>    /home/m1ke/tmp/php-zmq/modules
> 
> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the `-LLIBDIR'
> flag during linking and do at least one of the following:
>    - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
>      during execution
>    - add LIBDIR to the `LD_RUN_PATH' environment variable
>      during linking
>    - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
>    - have your system administrator add LIBDIR to `/etc/ld.so.conf'
> 
> See any operating system documentation about shared libraries for
> more information, such as the ld(1) and ld.so(8) manual pages.
> 
> Build complete.
> Don't forget to run 'make test'.
> 
> ERROR: Cannot run tests without CLI sapi.

**Comment by zprisk** [comment] 2016-01-07 17:54
@M1ke Honestly, I use sudo due to my lack of experience in working at this level (i.e.: installing PHP extensions, etc). 

Based on your output of make test regarding the libtool, you may need to install it yet:
sudo apt-get install libtool

I already have this library on my server, so that is why it is commented out (towards the top of my script).

Regarding:
ERROR: Cannot run tests without CLI sapi.

That is what I initially get, too, I rectify this by modifying the Makefile, again I can't explain as to why, but what I do is:
cd /etc/php-zmq
sudo nano Makefile
and then i change:
PHP_EXECUTABLE = /usr/bin/php from (PHP_EXECUTABLE = NONE)

This is something that I never had to do with using php 5.6, so not sure why it is needed here. I assume something is wrong somewhere....

However, after doing that change, I am able to run 'make test', which it runs the tests and then it successfully runs 53 tests: 11 skipped, 41 passed, and then only 1 fail (Test clearing and reusing ZMQPoll [tests/013-pollclearandreuse.phpt])

**Comment by M1ke** [comment] 2016-01-07 18:12
Ah, I had changed that value but I think another run had reset the `Makefile`. Adding that means the tests now run and I get the same error as you:

> Test clearing and reusing ZMQPoll [tests/013-pollclearandreuse.phpt]

I wonder is this enough to cause a segfault when actually trying to use the extension.

**Comment by zprisk** [comment] 2016-01-07 18:16
@M1ke When I attempt to use the extension (which I can confirm worked great in 5.6) I do get a segment fault at this point:
$receiverSocket = $context->getSocket(ZMQ::SOCKET_PULL);

Which makes sense, because the POLL test is failing.

I started an issue that is related specific to that here: 
https://github.com/mkoppanen/php-zmq/issues/165

You can see a lot of the results issues that I came up with in my debug attempts there.

**Comment by M1ke** [comment] 2016-01-07 18:23
OK thanks; I can see a lot of the info you gave me is there too. I will continue my discussion and post more information in that issue.

**Comment by mkoppanen** [comment] 2016-01-09 01:44
The relevant issue #165 has been closed now. Please open any PHP7 issues separately

**Closed by mkoppanen** 2016-01-09 01:44 UTC
